server:
  contextPath: /prototype
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/prototype
    username: prototype
    password: prototype
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false